
name: Build Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-01-13
    steps:
    - uses: actions/checkout@v1
    - name: main build
      run: make
